version: "3.9"

services:
  boekhoud_app:
    build: https://github.com/jayvenco/boekhoud.git
    container_name: boekhoud_app_v3
    ports:
      - "5000:5000"
    environment:
      # openssl rand -hex 24
      - OPENAI_API_KEY=
      - SECRET_KEY=
      - FLASK_ENV=production
    volumes:
      # Persistente opslag buiten de container
      - /mnt/user/appdata/boekhoud/data:/app/data
      - /mnt/user/appdata/boekhoud/uploads:/app/uploads
      - /mnt/user/appdata/boekhoud/backups:/app/backups
    user: "0:0"
    restart: unless-stopped
    # Veiligheid: beperk systeemrechten
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp

#volumes:
#  boekhoud_data:
#  boekhoud_uploads:
#  boekhoud_backups:
